title: <p align="center"> Vincent Vo </p>

logo: "/Images/main_logo.jpg?raw=true"

description:

  <p>
  IT Systems Administrator
  <br>
  IAM Advocate
  <br>
  </p>

  <p>
  <a href="https://www.linkedin.com/in/vovincent12/" target="_blank" style="gap:5px;"><img src="https://cdn-icons-png.flaticon.com/512/174/174857.png" alt=LinkedIn Icon" style="width:16px; height:16px;">LinkedIn</a>
  <br>
  <a href="https://github.com/venh-vo" target="_blank" style="gap:5px;><img src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" alt="Github Icon" style="width:16px; height:16px">GitHub</a>
  </p>
  
theme: jekyll-theme-minimal
# google_analytics: UA-145578661-1 # Google Analytics tracking ID
# <a href="pdf/resume.pdf">Resume</a> |